### ISSUE TITLE
Minor suggestions

### ISSUE THREAD

**Issue by matsstaff** [telefax/Pac-manager-Dependency-installer-for-CentOS-7#1]
Thanks a lot for this! Made setting up the PAC a lot easier!
I have two minor suggestions.
Add a shebang at the top e.g. **#!/bin/bash**
and maybe add **set -eu** after that, to make the script fail if one of the commands fail.

Thanks again!

**Comment by telefax** [comment]
Thanks. Implemented a few years too late. I'm a fantastic maintainer :o)
